---
title: "CNKI tables"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(flextable)
library(data.table)
library(officer)
library(tidyverse)
library(glue)
library(here)
library(knitr)
library(kableExtra)
here <- rprojroot::find_rstudio_root_file()

data <- as.data.table(readxl::read_xlsx(glue("{here}/out/cnki/sixing_sihuan_cites_downloads_pianming_guanjianci_zhaiyao.xlsx")))

tbl_a <- data[category == "Most downloaded Xi era", .(title_en, author_en, journal_en, pubdate, cites, downloads)][1:10]
tbl_b <- data[category == "Most cited Xi era", .(title_en, author_en, journal_en, pubdate, cites, downloads)][1:10]
tbl_c <- data[category == "Most downloaded Hu era", .(title_en, author_en, journal_en, pubdate, cites, downloads)][1:10]
tbl_d <- data[category == "Most cited Hu era", .(title_en, author_en, journal_en, pubdate, cites, downloads)][1:10]


## MAKE REFERENCES FROM THE CNKI CITATIONSS. JULY 26, 2022.
# Get the raw citations from the most cited Xi era table
xi_era <- data[category == "Most cited Xi era"][1:10]
xi_era$title
cnki_all <- fread("/Volumes/t7/projects/cnki_database/tbls/merged/tbl_final_articles.csv")
matched <- cnki_all[xi_era, on = c("title_ch" = "title")][document_id %notlike% "CJFD2014_JCSJ2014150"]
# matched %>% fwrite(glue("{here}/out/cnki/table_1_original.csv"))

# Markdown-formatted recently. 
glue("{matched$author_en} ({matched$journal_year}). {matched$i.title_en} [{matched$title_ch}]. *{matched$journal_en}* {matched$journal_issue}.  <br><br>")

# These are then pasted into https://markdowntohtml.com/ and then integrated into the reference list. 

####################

```


**Most downloaded Xi era**

```{r echo = FALSE, results="asis"}
knitr::kable(tbl_a, format="html") |>  kable_material(c("striped"))
```
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
**Most cited Xi era**

```{r echo = FALSE, results="asis"}
knitr::kable(tbl_b, format="html") |>  kable_material(c("striped"))
```

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

**Most downloaded Hu era**

```{r echo = FALSE, results="asis"}
knitr::kable(tbl_c, format="html") |>  kable_material(c("striped"))
```

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
**Most cited Hu era**

```{r echo = FALSE, results="asis"}
knitr::kable(tbl_d, format="html") |>  kable_material(c("striped"))
```

